/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hamaker2.particleSizeDistribution;

import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author uli
 */
public class FromFileDialog extends javax.swing.JDialog {

    /**
     * Creates new form FromFileDialog
     * @param psd
     */
    public FromFileDialog(FromFile psd) {
        super((java.awt.Frame)null, true);
        
        m_tableData = new FileTableModel();
        m_psdToEdit = psd;
        
        initComponents();
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        selectCard = new javax.swing.JPanel();
        fileChooser = new javax.swing.JFileChooser();
        loadCard = new javax.swing.JPanel();
        o_sizeType = new javax.swing.JComboBox();
        o_sizeUnit = new javax.swing.JComboBox();
        o_freqType = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        o_dataTable = new javax.swing.JTable();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        o_sizeCol = new javax.swing.JComboBox<String>();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        o_freqCol = new javax.swing.JComboBox<String>();
        o_backButton = new javax.swing.JButton();
        o_loadButton = new javax.swing.JButton();
        o_filePath = new javax.swing.JLabel();
        o_startRow = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mainPanel.setLayout(new java.awt.CardLayout());

        selectCard.setName("selectCard"); // NOI18N

        fileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout selectCardLayout = new javax.swing.GroupLayout(selectCard);
        selectCard.setLayout(selectCardLayout);
        selectCardLayout.setHorizontalGroup(
            selectCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectCardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        selectCardLayout.setVerticalGroup(
            selectCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectCardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        mainPanel.add(selectCard, "selectCard");

        loadCard.setName("loadCard"); // NOI18N

        o_sizeType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Diameter", "Radius" }));

        o_sizeUnit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "nm", "µm", "mm", "m" }));

        o_freqType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Number", "Cummulative number", "Volume", "Cummulative volume" }));

        jScrollPane1.setRowHeaderView(null);

        o_dataTable.setModel(m_tableData);
        jScrollPane1.setViewportView(o_dataTable);

        jLabel3.setText("Size in column:");

        jLabel4.setText("Type:");

        jLabel5.setText("Unit:");

        o_sizeCol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Frequency in column:");

        jLabel7.setText("Type:");

        o_freqCol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        o_backButton.setText("Back");
        o_backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_backButtonActionPerformed(evt);
            }
        });

        o_loadButton.setText("Load");
        o_loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_loadButtonActionPerformed(evt);
            }
        });

        o_filePath.setText("File: ");

        o_startRow.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        jLabel1.setText("Start import in row:");

        javax.swing.GroupLayout loadCardLayout = new javax.swing.GroupLayout(loadCard);
        loadCard.setLayout(loadCardLayout);
        loadCardLayout.setHorizontalGroup(
            loadCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loadCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loadCardLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(o_backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(o_loadButton))
                    .addComponent(o_filePath)
                    .addGroup(loadCardLayout.createSequentialGroup()
                        .addGroup(loadCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addGroup(loadCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(loadCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loadCardLayout.createSequentialGroup()
                                .addComponent(o_startRow, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(loadCardLayout.createSequentialGroup()
                                .addGroup(loadCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(o_sizeCol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(o_sizeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(o_sizeUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(loadCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(loadCardLayout.createSequentialGroup()
                                        .addGap(101, 101, 101)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(o_freqType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(loadCardLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(o_freqCol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        loadCardLayout.setVerticalGroup(
            loadCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loadCardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(o_filePath)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loadCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(o_startRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loadCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(o_sizeCol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o_freqCol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loadCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(o_sizeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(o_freqType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loadCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(o_sizeUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loadCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(o_backButton)
                    .addComponent(o_loadButton))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        mainPanel.add(loadCard, "loadCard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserActionPerformed
        if (evt.getActionCommand().equalsIgnoreCase("CancelSelection")) {
            this.setVisible(false);
        } else if (evt.getActionCommand().equalsIgnoreCase("ApproveSelection")) {
            o_filePath.setText(fileChooser.getSelectedFile().getAbsolutePath());
            loadDataIntoTable(fileChooser.getSelectedFile());
            ((CardLayout)(mainPanel.getLayout())).last(mainPanel);
            
            //prepare the start row spinner
            SpinnerNumberModel m = (SpinnerNumberModel) o_startRow.getModel();
            m.setMaximum(m_tableData.getRowCount());
            if ((int)(m.getValue()) > m_tableData.getRowCount()) {
                m.setValue(m_tableData.getRowCount());
            }
            //maybe set first non hashed row?
            
            //prepare the column selection popups
            o_sizeCol.removeAllItems();
            o_freqCol.removeAllItems();
            for (int i=0;i<m_tableData.getColumnCount()-1;i++) {
                o_sizeCol.addItem(m_tableData.getColumnName(i+1));
                o_freqCol.addItem(m_tableData.getColumnName(i+1));
            }
            o_sizeCol.setSelectedIndex(0);
            if (m_tableData.getColumnCount() > 2) {
                o_freqCol.setSelectedIndex(1);
            } else {
                o_freqCol.setSelectedIndex(0);
            }
            
            //set GUI buttons
            getRootPane().setDefaultButton(o_loadButton);
            /*getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ESCAPE"), "cancelAction");
            getRootPane().getActionMap().put("cancelAction", new AbstractAction() {
                @Override
                public void actionPerformed(ActionEvent ae) {
                    ((CardLayout)(mainPanel.getLayout())).first(mainPanel);
                    getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).remove(KeyStroke.getKeyStroke("ESCAPE"));
                    System.out.println("In cancel button");
                }
            });*/
        }
    }//GEN-LAST:event_fileChooserActionPerformed

    private void o_loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_loadButtonActionPerformed
        int startRow = (int)o_startRow.getValue() - 1;
        int numPoints = m_tableData.getRowCount() - startRow;
        double[] diameters = new double[numPoints];
        double[] numberFractions = new double[numPoints];
        
        double cumm_prev = 0.0;
        double volFracSum = 0.0;
        
        for (int i=0;i<numPoints;i++) {
            //get the raw values
            String size_str = (String)m_tableData.getValueAt(i + startRow, o_sizeCol.getSelectedIndex() + 1);
            String freq_str = (String)m_tableData.getValueAt(i + startRow, o_freqCol.getSelectedIndex() + 1);
            double size = Double.parseDouble(size_str);
            double freq = Double.parseDouble(freq_str);
            
            //treat size type
            if (o_sizeType.getSelectedItem().equals("Diameter")) {
                //just keep it, it's already fine
            } else if (o_sizeType.getSelectedItem().equals("Radius")) {
                size *= 2;
            } else {
                System.out.println("Unknown size type: " + o_sizeType.getSelectedItem());
            }
            
            //treat size unit
            if (o_sizeUnit.getSelectedItem().equals("nm")) {
                size *= 1E-9;
            } else if (o_sizeUnit.getSelectedItem().equals("µm")) {
                size *= 1E-6;
            } else if (o_sizeUnit.getSelectedItem().equals("mm")) {
                size *= 1E-3;
            } else if (o_sizeUnit.getSelectedItem().equals("m")) {
                //just keep it, it's already fine
            } else {
                System.out.println("Unknown size unit: " + o_sizeUnit.getSelectedItem());
            }
            
            
            if (o_freqType.getSelectedItem().equals("Number")) {
                //just keep it, it's already fine
            } else if (o_freqType.getSelectedItem().equals("Cummulative number")) {
                //deduct previous fraction
                double temp = cumm_prev;
                cumm_prev = freq;
                freq -= temp;
            } else if (o_freqType.getSelectedItem().equals("Volume")) {
                //I still have to post multiply with the sum of all volume fractions, so accumulate it
                volFracSum += freq;
                //convert to number
                freq /= 4.0 / 3.0 * Math.PI * size * size * size / 8.0;
            } else if (o_freqType.getSelectedItem().equals("Cummulative volume")) {
                //deduct previous fraction
                double temp = cumm_prev;
                cumm_prev = freq;
                freq -= temp;
                //now I have the proper volume fraction, proceed as above
                //I still have to post multiply with the sum of all volume fractions, so accumulate it
                volFracSum += freq;
                //convert to number
                freq /= 4.0 / 3.0 * Math.PI * size * size * size / 8.0;
            } else {
                System.out.println("Unknown frequency type: " + o_freqType.getSelectedItem());
            }
                        
            diameters[i] = size;
            numberFractions[i] = freq;
        }
        
        //check if post fix is needed
        if (o_freqType.getSelectedItem().equals("Volume") || o_freqType.getSelectedItem().equals("Cummulative Volume")) {
            for (int i=0;i<numPoints;i++) {
                numberFractions[i] *= volFracSum;
            }
        }
                
        m_psdToEdit.setData(o_filePath.getText(), numPoints, diameters, numberFractions);
        
        this.setVisible(false);
    }//GEN-LAST:event_o_loadButtonActionPerformed

    private void o_backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_backButtonActionPerformed
            ((CardLayout)(mainPanel.getLayout())).first(mainPanel);
    }//GEN-LAST:event_o_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel loadCard;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton o_backButton;
    private javax.swing.JTable o_dataTable;
    private javax.swing.JLabel o_filePath;
    private javax.swing.JComboBox<String> o_freqCol;
    private javax.swing.JComboBox o_freqType;
    private javax.swing.JButton o_loadButton;
    private javax.swing.JComboBox<String> o_sizeCol;
    private javax.swing.JComboBox o_sizeType;
    private javax.swing.JComboBox o_sizeUnit;
    private javax.swing.JSpinner o_startRow;
    private javax.swing.JPanel selectCard;
    // End of variables declaration//GEN-END:variables

    private final FileTableModel m_tableData;
    private final FromFile m_psdToEdit;
    
    private void loadDataIntoTable(File selectedFile) {
        try (BufferedReader input = new BufferedReader(new java.io.FileReader(selectedFile))) {
            
            m_tableData.load(input);
            
            
        } catch (IOException ex) {
            Logger.getLogger(FromFileDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private class FileTableModel extends AbstractTableModel {

        ArrayList<ArrayList<String>> m_data;
        
        public FileTableModel() {
            m_data = new ArrayList<>();
        }
        
        public void load(BufferedReader input) throws IOException {
            m_data.clear();
            while (input.ready()) {
                String line = input.readLine();
                String[] elements = line.split("\\s+");
                ArrayList<String> row = new ArrayList<>();
                row.addAll(Arrays.asList(elements));
                m_data.add(row);
                this.fireTableStructureChanged();
            }
        }
        
        @Override
        public int getRowCount() {
            return m_data.size();
        }

        @Override
        public int getColumnCount() {
            int max = 0;
            for (ArrayList<String> row : m_data) {
                max = Math.max(max, row.size());
            }
            return max + 1;
        }
        
        @Override
        public String getColumnName(int column) {
            if (column == 0) {
                return "Row";
            } else {
                return super.getColumnName(column-1);
            }
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            if (rowIndex >= m_data.size()) {
                return "";
            } else {
                if (columnIndex == 0) {
                    return String.valueOf(rowIndex + 1);
                } else if (columnIndex > m_data.get(rowIndex).size()) {
                    return "";
                } else {
                    return m_data.get(rowIndex).get(columnIndex - 1);
                }
            }
        }
    }
        
}
