/*
 * HamakerConstantDialog.java
 *
 * Created on May 13, 2007, 8:33 AM
 */
package hamaker2;

import java.awt.event.ActionEvent;
import java.io.*;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.*;

/**
 * Class to show a dialog for the selection of Hamaker constants from online
 * repository
 *
 * @author uli
 */
public class HamakerConstantDialog extends javax.swing.JDialog {

    /**
     * Creates new form HamakerConstantDialog
     *
     * @param parent Parent window to show this above
     * @param modal Should dialog be modal
     */
    public HamakerConstantDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        m_model = new HamakerTableModel();
        m_particleToEdit = null;

        initComponents();

        getRootPane().setDefaultButton(use);
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ESCAPE"), "cancelAction");
        getRootPane().getActionMap().put("cancelAction", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                setVisible(false);
                m_particleToEdit = null;
            }
        });
    }

    /**
     * Show the dialog modifying a given particle
     *
     * @param particle The particle to be modified
     */
    public void showForParticle(Particle particle) {
        m_particleToEdit = particle;
        use.setEnabled(false);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(m_model) {
            public void valueChanged(ListSelectionEvent e) {
                super.valueChanged(e);
                use.setEnabled(getSelectedRow() != -1);
            }
        };
        use = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        refresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(m_model);
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        use.setText("Use Constant");
        use.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        refresh.setText("Get from Internet");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(cancel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(use))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, refresh))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(refresh)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(use)
                    .add(cancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        m_model.load();
        jTable1.repaint();
    }//GEN-LAST:event_refreshActionPerformed

    private void useActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useActionPerformed
        m_particleToEdit.setHamakerConstantFromText(((String) (m_model.getValueAt(jTable1.getSelectedRow(), 6))));

        setVisible(false);
        m_particleToEdit = null;
    }//GEN-LAST:event_useActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        setVisible(false);
        m_particleToEdit = null;
    }//GEN-LAST:event_cancelActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        //dirty way to make dialog respond to enter events
        if (evt.getKeyChar() == 10) {
            use.dispatchEvent(evt);
        }
    }//GEN-LAST:event_jTable1KeyPressed
    HamakerTableModel m_model;
    Particle m_particleToEdit;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton refresh;
    private javax.swing.JButton use;
    // End of variables declaration//GEN-END:variables

    private class HamakerTableModel extends AbstractTableModel {

        private final ArrayList<HamakerEntry> m_entries;

        public HamakerTableModel() {
            m_entries = new ArrayList<>();
        }

        public void load() {
            try {
                URL location = new URL("https://raw.githubusercontent.com/uliaschauer/hamaker2/refs/heads/main/hamaker.dat");
                BufferedReader input = new BufferedReader(new InputStreamReader(location.openStream()));

                while (input.ready()) {
                    String line = input.readLine();
                    String[] fields = line.split("\t");

                    if (fields.length == 4) {
                        m_entries.add(new HamakerEntry(fields));
                    }
                }

            } catch (FileNotFoundException ex) {
            } catch (IOException ex) {
            }

            this.fireTableDataChanged();
        }

        @Override
        public int getColumnCount() {
            return 4;
        }

        @Override
        public int getRowCount() {
            return m_entries.size();
        }

        @Override
        public String getColumnName(int col) {
            switch (col) {
                case 0:
                    return "Description";
                case 1:
                    return "Material";
                case 2:
                    return "Reference";
                case 3:
                    return "Constant";
                default:
                    return "Undefined";
            }
        }

        @Override
        public Object getValueAt(int h, int v) {

            switch (v) {
                case 0:
                    return m_entries.get(h).m_descrption;
                case 1:
                    return m_entries.get(h).m_material;
                case 2:
                    return m_entries.get(h).m_reference;
                case 3:
                    return String.valueOf(m_entries.get(h).m_constant);
                default:
                    return "Undefined";
            }
        }

        private class HamakerEntry {

            String m_descrption;
            String m_material;
            String m_reference;
            double m_constant;

            public HamakerEntry(String[] fields) {
                m_descrption = fields[0];
                m_material = fields[1];
                m_reference = fields[2];
                m_constant = Utils.StringToDouble(fields[3]);
            }
        }
    }
}
