/*
 * MediumDialog.java
 *
 * Created on April 4, 2007, 4:52 PM
 */
package hamaker2;

import java.awt.event.ActionEvent;
import java.text.DecimalFormat;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.*;

/**
 * Dialog to set medium parameters
 *
 * @author uli
 */
public class MediumDialog extends javax.swing.JDialog implements ListSelectionListener {

    /**
     * Creates new form MediumDialog
     *
     * @param parent Parent window to show this dialog above
     * @param modal Is dialog modal
     */
    public MediumDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        m_tableModel = new MediumTableModel();

        initComponents();

        rootPane.setDefaultButton(o_okButton);
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ESCAPE"), "cancelAction");
        getRootPane().getActionMap().put("cancelAction", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                setVisible(false);
                m_mediumToEdit = null;
            }
        });

        o_electrolyteTable.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);

        m_mediumToEdit = null;
        m_saveMedium = null;
        m_temp = 300.0;
    }

    /**
     * Show the dialog for the given dispersion medium
     *
     * @param medium Medium to be edited
     */
    public void showForMedium(Medium medium) {
        m_mediumToEdit = medium;

        //save a copy in order to restore the electrolyte when canceling
        m_saveMedium = Medium.newInstance(medium);

        o_density.setText(m_mediumToEdit.getDensityAsText());
        o_dielectricConstant.setText(m_mediumToEdit.getDielectricConstantAsText());

        updateKappa();

        o_deleteButton.setEnabled(o_electrolyteTable.getRowCount() > 0 && o_electrolyteTable.getSelectedRowCount() > 0);
        o_electrolyteTable.setRowSelectionInterval(0, 0);

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        o_density = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        o_okButton = new javax.swing.JButton();
        o_cancelButton = new javax.swing.JButton();
        o_dielectricConstant = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        o_debye = new javax.swing.JLabel();
        o_addButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        o_electrolyteTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        o_temp = new javax.swing.JTextField();
        o_deleteButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setModal(true);
        setName("Define Medium"); // NOI18N
        setResizable(false);

        jLabel1.setText("Density:");

        o_density.setText("JTextField1");

        jLabel3.setText("<html>g/cm<sup>3</sup></html>");

        o_okButton.setText("OK");
        o_okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_okButtonActionPerformed(evt);
            }
        });

        o_cancelButton.setText("Cancel");
        o_cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_cancelButtonActionPerformed(evt);
            }
        });

        o_dielectricConstant.setText("JTextField1");
        o_dielectricConstant.setActionCommand("<Not Set>");
        o_dielectricConstant.setAutoscrolls(false);
        o_dielectricConstant.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                o_dielectricConstantPropertyChange(evt);
            }
        });

        jLabel4.setText("Dielectric Constant:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Electrolyte Composition")));

        o_debye.setText("jLabel6");

        o_addButton.setText("Add");
        o_addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_addButtonActionPerformed(evt);
            }
        });

        o_electrolyteTable.setModel(m_tableModel);
        o_electrolyteTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        o_electrolyteTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                o_electrolyteTableKeyPressed(evt);
            }
        });
        o_electrolyteTable.getSelectionModel().addListSelectionListener(this);
        jScrollPane1.setViewportView(o_electrolyteTable);

        jLabel5.setText("Debye length at");

        o_temp.setText("300");
        o_temp.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                o_tempPropertyChange(evt);
            }
        });

        o_deleteButton.setText("Delete");
        o_deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_deleteButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("K:");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(6, 6, 6)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel5)
                                .add(18, 18, 18)
                                .add(o_temp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel6)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(o_debye))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(o_addButton)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(o_deleteButton)))
                        .add(0, 199, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .add(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(o_addButton)
                    .add(o_deleteButton))
                .add(6, 6, 6)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 166, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(6, 6, 6)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(o_temp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6)
                    .add(o_debye)))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(6, 6, 6)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .add(jLabel1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(o_density, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(jLabel4)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(o_dielectricConstant, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(0, 0, Short.MAX_VALUE)
                                .add(o_cancelButton)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(o_okButton)))
                        .add(6, 6, 6))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(6, 6, 6)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(o_dielectricConstant, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(o_density, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1)
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(o_okButton)
                    .add(o_cancelButton))
                .add(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void o_okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_okButtonActionPerformed
        m_mediumToEdit.setDensityFromText(o_density.getText());
        m_mediumToEdit.setDielectricConstantFromText(o_dielectricConstant.getText());

        setVisible(false);
        m_mediumToEdit = null;
        m_saveMedium = null;
    }//GEN-LAST:event_o_okButtonActionPerformed

    private void o_cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_cancelButtonActionPerformed

        //restore the electrolyte
        //first remove all that's there
        m_mediumToEdit.deleteAllElectrolyteComponents();
        //now copy in the saved ones
        for (int i = 0; i < m_saveMedium.getNumElectrolyteComponents(); i++) {
            m_mediumToEdit.addElectrolyteComponent(m_saveMedium.getElectrolyteComponentLabel(i), m_saveMedium.getElectrolyteComponentValence(i), m_saveMedium.getElectrolyteComponentConcentration(i));
        }

        setVisible(false);
        m_mediumToEdit = null;
        m_saveMedium = null;
    }//GEN-LAST:event_o_cancelButtonActionPerformed

    private void o_deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_deleteButtonActionPerformed
        if (o_electrolyteTable.getRowCount() > 1) {
            m_mediumToEdit.deleteElectrolyteComponent(o_electrolyteTable.getSelectedRow());
            o_electrolyteTable.updateUI();
            o_deleteButton.setEnabled(o_electrolyteTable.getRowCount() > 0 && o_electrolyteTable.getSelectedRowCount() > 0 && o_electrolyteTable.getSelectedRow() < o_electrolyteTable.getRowCount());
            updateKappa();
        } else {
            JOptionPane.showMessageDialog(this, "Your electrolyte needs to contain at least one species!", "Cannot delete species", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_o_deleteButtonActionPerformed

    private void o_addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_addButtonActionPerformed
        m_mediumToEdit.addElectrolyteComponent();
        o_electrolyteTable.updateUI();
        o_deleteButton.setEnabled(o_electrolyteTable.getRowCount() > 0 && o_electrolyteTable.getSelectedRowCount() > 0);
        updateKappa();
    }//GEN-LAST:event_o_addButtonActionPerformed

    private void o_dielectricConstantPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_o_dielectricConstantPropertyChange
        if (m_mediumToEdit != null) {
            m_mediumToEdit.setDielectricConstantFromText(o_dielectricConstant.getText());
            updateKappa();
        }
    }//GEN-LAST:event_o_dielectricConstantPropertyChange

    private void o_tempPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_o_tempPropertyChange
        m_temp = Double.valueOf(o_temp.getText()).doubleValue();
        updateKappa();
    }//GEN-LAST:event_o_tempPropertyChange

    private void o_electrolyteTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_o_electrolyteTableKeyPressed
        //dirty way to make the dialog respond to enter events
        if (evt.getKeyCode() == 10) {
            o_okButton.dispatchEvent(evt);
        }
    }//GEN-LAST:event_o_electrolyteTableKeyPressed

    private void updateKappa() {
        if (m_mediumToEdit != null) {
            o_debye.setText(new DecimalFormat("0.00").format(m_mediumToEdit.debye(m_temp) * 1E9) + " nm");
        }
    }

    @Override
    public void valueChanged(ListSelectionEvent lse) {
        o_deleteButton.setEnabled(o_electrolyteTable.getRowCount() > 0 && o_electrolyteTable.getSelectedRowCount() > 0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton o_addButton;
    private javax.swing.JButton o_cancelButton;
    private javax.swing.JLabel o_debye;
    private javax.swing.JButton o_deleteButton;
    private javax.swing.JTextField o_density;
    private javax.swing.JTextField o_dielectricConstant;
    private javax.swing.JTable o_electrolyteTable;
    private javax.swing.JButton o_okButton;
    private javax.swing.JTextField o_temp;
    // End of variables declaration//GEN-END:variables
    Medium m_mediumToEdit;
    MediumTableModel m_tableModel;
    Medium m_saveMedium;
    double m_temp;

    private class MediumTableModel extends AbstractTableModel {

        @Override
        public int getColumnCount() {
            return 3;
        }

        @Override
        public int getRowCount() {
            if (m_mediumToEdit == null) {
                return 0;
            } else {
                return m_mediumToEdit.getNumElectrolyteComponents();
            }
        }

        @Override
        public String getColumnName(int column) {
            String names[] = {"Label", "Valence [e]", "Concentration [M]"};
            return names[column];
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            switch (columnIndex) {
                case 0:
                    return m_mediumToEdit.getElectrolyteComponentLabel(rowIndex);
                case 1:
                    return m_mediumToEdit.getElectrolyteComponentValence(rowIndex);
                case 2:
                    return m_mediumToEdit.getElectrolyteComponentConcentration(rowIndex);
            }

            return "Error";
        }

        @Override
        public boolean isCellEditable(int row, int col) {
            return true;
        }

        @Override
        public void setValueAt(Object aValue, int rowIndex, int columnIndex) {
            switch (columnIndex) {
                case 0:
                    m_mediumToEdit.setElectrolyteComponentLabel(rowIndex, (String) aValue);
                    break;
                case 1:
                    m_mediumToEdit.setElectrolyteComponentValence(rowIndex, Utils.StringToDouble((String) aValue));
                    break;
                case 2:
                    m_mediumToEdit.setElectrolyteComponentConcentration(rowIndex, Utils.StringToDouble((String) aValue));
                    break;
            }

            updateKappa();
        }
    }
}
