/*
 * MiscDialog.java
 *
 * Created on April 12, 2007, 8:31 AM
 */
package hamaker2;

import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.*;

/**
 * Class to show the misc models dialog
 *
 * @author uli
 */
public class MiscDialog extends javax.swing.JDialog implements ListSelectionListener {

    /**
     * Creates new form MiscDialog
     *
     * @param parent Parent component to show this dialog above
     * @param modal Is dialog modal
     */
    public MiscDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        m_tableModel = new MiscTableModel();

        initComponents();

        rootPane.setDefaultButton(o_okButton);
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ESCAPE"), "cancelAction");
        getRootPane().getActionMap().put("cancelAction", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                setVisible(false);
                m_serieToEdit = null;
            }
        });

        m_serieToEdit = null;
        m_saveSerie = null;
    }

    /**
     * Show this dialog for a given data series
     *
     * @param serie Series to be edited
     */
    public void showForSerie(Serie serie) {
        m_serieToEdit = serie;
        m_saveSerie = Serie.newInstance(serie);

        o_activeBox.setEnabled(false);
        o_additionalParamsButton.setEnabled(false);

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        o_modelTable = new javax.swing.JTable();
        o_activeBox = new javax.swing.JCheckBox();
        o_additionalParamsButton = new javax.swing.JButton();
        o_okButton = new javax.swing.JButton();
        o_cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        o_modelTable.setModel(m_tableModel);
        o_modelTable.setSurrendersFocusOnKeystroke(true);
        o_modelTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        ListSelectionModel rowSM = o_modelTable.getSelectionModel();
        rowSM.addListSelectionListener(this);
        o_modelTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                o_modelTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(o_modelTable);

        o_activeBox.setText("Active");
        o_activeBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        o_activeBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        o_activeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_activeBoxActionPerformed(evt);
            }
        });

        o_additionalParamsButton.setText("Additional Parameters...");
        o_additionalParamsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_additionalParamsButtonActionPerformed(evt);
            }
        });

        o_okButton.setText("OK");
        o_okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_okButtonActionPerformed(evt);
            }
        });

        o_cancelButton.setText("Cancel");
        o_cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_cancelButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(6, 6, 6)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .add(6, 6, 6)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(o_activeBox)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(layout.createSequentialGroup()
                            .add(o_cancelButton)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(o_okButton))
                        .add(o_additionalParamsButton)))
                .add(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(6, 6, 6)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(o_activeBox)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(o_additionalParamsButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 380, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(o_okButton)
                            .add(o_cancelButton)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
                .add(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void o_activeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_activeBoxActionPerformed
        int row = o_modelTable.getSelectedRow();

        m_serieToEdit.getMiscModel(row).setActive(o_activeBox.isSelected());
    }//GEN-LAST:event_o_activeBoxActionPerformed

    private void o_additionalParamsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_additionalParamsButtonActionPerformed
        int row = o_modelTable.getSelectedRow();
        m_serieToEdit.getMiscModel(row).showMoreDialog();
    }//GEN-LAST:event_o_additionalParamsButtonActionPerformed

    private void o_cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_cancelButtonActionPerformed
        //restore if canceled
        m_serieToEdit.setMiscModels(m_saveSerie.getMiscModels());

        setVisible(false);
        m_serieToEdit = null;
        m_saveSerie = null;
    }//GEN-LAST:event_o_cancelButtonActionPerformed

    private void o_okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_okButtonActionPerformed
        setVisible(false);
        m_serieToEdit = null;
        m_saveSerie = null;
    }//GEN-LAST:event_o_okButtonActionPerformed

    private void o_modelTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_o_modelTableKeyPressed
        //dirty way to make sure the ok button can be triggered by enter key
        if (evt.getKeyCode() == 10) {
            o_okButton.dispatchEvent(evt);
        }
    }//GEN-LAST:event_o_modelTableKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox o_activeBox;
    private javax.swing.JButton o_additionalParamsButton;
    private javax.swing.JButton o_cancelButton;
    private javax.swing.JTable o_modelTable;
    private javax.swing.JButton o_okButton;
    // End of variables declaration//GEN-END:variables
    Serie m_serieToEdit;
    Serie m_saveSerie;
    MiscTableModel m_tableModel;

    @Override
    public void valueChanged(ListSelectionEvent e) {
        if (e.getValueIsAdjusting()) {
            return;
        }

        ListSelectionModel lsm = (ListSelectionModel) e.getSource();
        if (lsm.isSelectionEmpty()) {
            o_activeBox.setEnabled(false);
            o_activeBox.setSelected(false);
            o_additionalParamsButton.setEnabled(false);
        } else {
            int row = lsm.getMinSelectionIndex();

            if (m_serieToEdit.getMiscModel(row).ImplementedGeometryClasses().contains(m_serieToEdit.getSelectedGeometryClass())) {
                o_activeBox.setEnabled(true);
                o_activeBox.setSelected(m_serieToEdit.getMiscModel(row).getActive());
                o_additionalParamsButton.setEnabled(m_serieToEdit.getMiscModel(row).additionalParameters());
            } else {
                o_activeBox.setEnabled(false);
                o_activeBox.setSelected(false);
                o_additionalParamsButton.setEnabled(false);
            }
        }
    }

    private class MiscTableModel extends AbstractTableModel {

        @Override
        public int getColumnCount() {
            return 1;
        }

        @Override
        public int getRowCount() {
            if (m_serieToEdit == null) {
                return 0;
            } else {
                return m_serieToEdit.getMiscModelCount();
            }
        }

        @Override
        public String getColumnName(int column) {
            String names[] = {"Model"};
            return names[column];
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            switch (columnIndex) {
                case 0:
                    return m_serieToEdit.getMiscModel(rowIndex).name();
            }

            return "Error";
        }

        @Override
        public boolean isCellEditable(int row, int col) {
            return false;
        }

        @Override
        public void setValueAt(Object aValue, int rowIndex, int columnIndex) {
        }
    }
}
