/*
 * StabilityDialog.java
 *
 * Created on 6. septembre 2007, 12:05
 */

package hamaker2;

import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 * Dialog to display the stability parameter dialog
 * @author  aschauer
 */
public class StabilityDialog extends javax.swing.JDialog {
    
    /**
     * Create a new instance of the stability dialog
     * @param parent Parent frame to display the dialog over
     * @param modal Is the dialog modal
     */
    public StabilityDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        getRootPane().setDefaultButton(o_ok);
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ESCAPE"), "cancelAction");
        getRootPane().getActionMap().put("cancelAction", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                setVisible(false);
                m_stability_to_edit = null;
            }
        });
                
        m_stability_to_edit = null;
        m_heterogeneous = false;
    }
    
    /**
     * Show the dialog for a given stability object and heterogeneity of the series
     * @param stability Stability object
     * @param heterogeneous Is the series heterogeneous
     */
    public void showForStability(Stability stability, boolean heterogeneous) {
        m_stability_to_edit = stability;
        m_heterogeneous = heterogeneous;
        
        if (m_heterogeneous) {
            o_p1_conc.setText(String.valueOf(m_stability_to_edit.getParticle1Concentration()));
            o_p2_conc.setText(String.valueOf(m_stability_to_edit.getParticle2Concentration()));
            o_p2_conc.setEnabled(true);
        } else {
            o_p1_conc.setText(String.valueOf(m_stability_to_edit.getParticle1Concentration()));
            o_p2_conc.setText(String.valueOf(0.00));
            o_p2_conc.setEnabled(false);
        }
        
        o_hours.setText(String.valueOf(m_stability_to_edit.getHours()));
        o_minutes.setText(String.valueOf(m_stability_to_edit.getMinutes()));
        o_viscous.setSelected(m_stability_to_edit.getViscous());
        
        setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        o_viscous = new javax.swing.JCheckBox();
        o_cancel = new javax.swing.JButton();
        o_ok = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        o_minutes = new javax.swing.JTextField();
        o_hours = new javax.swing.JTextField();
        o_p1_conc = new javax.swing.JTextField();
        o_p2_conc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel2.setText("Time (hh:mm):");

        o_viscous.setText("Viscous drag");
        o_viscous.setMargin(new java.awt.Insets(0, 0, 0, 0));

        o_cancel.setText("Cancel");
        o_cancel.setFocusable(false);
        o_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_cancelActionPerformed(evt);
            }
        });

        o_ok.setText("OK");
        o_ok.setFocusable(false);
        o_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_okActionPerformed(evt);
            }
        });

        jLabel1.setText("Particle 1 concentration:");

        jLabel3.setText("wt.%");

        jLabel4.setText("Particle 2 concentration:");

        jLabel5.setText("wt.%");

        o_minutes.setText("jTextField1");

        o_hours.setText("jTextField1");

        o_p1_conc.setText("jTextField2");

        o_p2_conc.setText("jTextField3");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(o_viscous)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(layout.createSequentialGroup()
                            .add(o_cancel)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(o_ok))
                        .add(layout.createSequentialGroup()
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(layout.createSequentialGroup()
                                    .add(jLabel1)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(o_p1_conc))
                                .add(layout.createSequentialGroup()
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jLabel4)
                                        .add(jLabel2))
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                        .add(layout.createSequentialGroup()
                                            .add(o_hours, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                            .add(o_minutes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(o_p2_conc))))
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jLabel5)
                                .add(jLabel3)))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(new java.awt.Component[] {o_hours, o_minutes}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(o_p1_conc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(o_p2_conc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(o_hours, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(o_minutes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(o_viscous)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(o_ok)
                    .add(o_cancel))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void o_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_cancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_o_cancelActionPerformed
    
    private void o_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_okActionPerformed
        if (m_heterogeneous) {
            m_stability_to_edit.setParticle1Concentration(Utils.StringToDouble(o_p1_conc.getText()));
            m_stability_to_edit.setParticle2Concentration(Utils.StringToDouble(o_p2_conc.getText()));
        }
        else
        {
            m_stability_to_edit.setParticle1Concentration(Utils.StringToDouble(o_p1_conc.getText()));
        }
        m_stability_to_edit.setHours(Integer.valueOf(o_hours.getText()).intValue());
        m_stability_to_edit.setMinutes(Integer.valueOf(o_minutes.getText()).intValue());
        m_stability_to_edit.setViscous(Boolean.valueOf(o_viscous.isSelected()).booleanValue());
        
        setVisible(false);
    }//GEN-LAST:event_o_okActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new StabilityDialog(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton o_cancel;
    private javax.swing.JTextField o_hours;
    private javax.swing.JTextField o_minutes;
    private javax.swing.JButton o_ok;
    private javax.swing.JTextField o_p1_conc;
    private javax.swing.JTextField o_p2_conc;
    private javax.swing.JCheckBox o_viscous;
    // End of variables declaration//GEN-END:variables
    
    private Stability m_stability_to_edit;
    private boolean m_heterogeneous;
}
