/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hamaker2;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.geom.Rectangle2D;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.KeyStroke;
import org.jfree.chart.ChartMouseEvent;
import org.jfree.chart.ChartMouseListener;
import org.jfree.chart.JFreeChart;
import org.jfree.data.xy.XYSeries;

/**
 * Class to display the YODEL parameter dialog
 *
 * @author asulrich
 */
public class YodelDialog extends javax.swing.JDialog implements ChartMouseListener {

    Serie m_editedSerie, m_saveSerie;

    /**
     * Creates new form YodelDialog
     *
     * @param parent Parent frame to show this dialog over
     * @param modal Is the dialog modal
     */
    public YodelDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        m_editedSerie = null;
        m_saveSerie = null;

        m_yodelPlotData = new org.jfree.data.xy.XYSeriesCollection();

        initComponents();

        rootPane.setDefaultButton(o_okButton);
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ESCAPE"), "cancelAction");
        getRootPane().getActionMap().put("cancelAction", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                if (isVisible()) {
                    setVisible(false);
                    m_editedSerie = m_saveSerie;
                    m_editedSerie = null;
                    m_saveSerie = null;
                }
            }
        });
    }

    /**
     * Show the dialog for the given series
     *
     * @param s Series to be edited
     */
    public void showForSerie(Serie s) {

        //locally save the serie to be edited
        m_editedSerie = s;

        //make a copy to use when cancelling
        m_saveSerie = Serie.newInstance(s);

        o_percolation.setText(String.valueOf(s.getYodel().getPercolationTreshold()));
        o_maxPack.setText(String.valueOf(s.getYodel().getMaxPackingFraction()));
        o_volumeFunction.setSelectedItem(s.getYodel().getVolumeIncrementFunction());

        o_radiusHarmonic.setSelected(s.getYodel().getHarmonicCurvature());
        o_radiusManual.setSelected(!s.getYodel().getHarmonicCurvature());
        o_contactRadius.setText(String.valueOf(s.getYodel().getCurvatureRadius() * 1E9));
        o_contactRadius.setEnabled(!s.getYodel().getHarmonicCurvature());
        o_harmRadius.setText(new DecimalFormat("0.0").format(s.averageHarmonicRadius() * 1E9));

        o_forceAutomatic.setSelected(s.getYodel().getAutoAttractiveForce());
        o_forceManual.setSelected(!s.getYodel().getAutoAttractiveForce());
        o_autoHamaker.setText(new DecimalFormat("0.00E00").format(s.getYodel().getAutoAttractiveHamaker(s)));
        o_autoSeparation.setText(new DecimalFormat("0.00").format(s.getYodel().getAutoAttractiveSeparation(s) * 1E9));
        o_manualHamaker.setText(new DecimalFormat("0.00E00").format(s.getYodel().getManualAttractiveHamaker()));
        o_manualHamaker.setEnabled(!s.getYodel().getAutoAttractiveForce());
        o_manualSeparation.setText(new DecimalFormat("0.00").format(s.getYodel().getManualAttractiveSeparation() * 1E9));
        o_manualSeparation.setEnabled(!s.getYodel().getAutoAttractiveForce());

        o_volFracSlider.setEnabled(s.getHeterogeneous());
        if (s.getHeterogeneous()) {
            o_volFrac1.setText(new DecimalFormat("0.00").format(s.getYodel().getParticle1VolumeFraction()));
            o_volFrac2.setText(new DecimalFormat("0.00").format(s.getYodel().getParticle2VolumeFraction()));
            o_volFracSlider.setValue((int) (s.getYodel().getParticle2VolumeFraction() * 100));
        } else {
            o_volFracSlider.setValue(0);
            o_volFrac1.setText("1.00");
            o_volFrac2.setText("0.00");
        }

        o_b_tilda_bug.setSelected(s.getYodel().bTildaBug());

        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        o_curvatureGroup = new javax.swing.ButtonGroup();
        o_forceGroup = new javax.swing.ButtonGroup();
        o_paintPanel = createPlotPanel();
        o_okButton = new javax.swing.JButton();
        o_cancelButton = new javax.swing.JButton();
        javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        o_percolation = new javax.swing.JTextField();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        o_maxPack = new javax.swing.JTextField();
        javax.swing.JLabel jLabel12 = new javax.swing.JLabel();
        o_volumeFunction = new javax.swing.JComboBox<Yodel.VolumeIncrementFunction>();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel13 = new javax.swing.JLabel();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        o_radiusManual = new javax.swing.JRadioButton();
        o_contactRadius = new javax.swing.JTextField();
        o_radiusHarmonic = new javax.swing.JRadioButton();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        o_harmRadius = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        o_b_tilda_bug = new javax.swing.JCheckBox();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        o_forceAutomatic = new javax.swing.JRadioButton();
        o_forceManual = new javax.swing.JRadioButton();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        o_manualSeparation = new javax.swing.JTextField();
        o_manualHamaker = new javax.swing.JTextField();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        o_autoHamaker = new javax.swing.JLabel();
        o_autoSeparation = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        o_model = new javax.swing.JComboBox<Yodel.Model>();
        jLabel16 = new javax.swing.JLabel();
        o_volFracSlider = new javax.swing.JSlider();
        o_volFrac1 = new javax.swing.JLabel();
        o_volFrac2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        o_paintPanel.setBackground(new java.awt.Color(255, 255, 255));

        org.jdesktop.layout.GroupLayout o_paintPanelLayout = new org.jdesktop.layout.GroupLayout(o_paintPanel);
        o_paintPanel.setLayout(o_paintPanelLayout);
        o_paintPanelLayout.setHorizontalGroup(
            o_paintPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 487, Short.MAX_VALUE)
        );
        o_paintPanelLayout.setVerticalGroup(
            o_paintPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
        );

        o_okButton.setText("OK");
        o_okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_okButtonActionPerformed(evt);
            }
        });

        o_cancelButton.setText("Cancel");
        o_cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_cancelButtonActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Parameters"));

        jLabel1.setText("Percolation treshold:");

        o_percolation.setText("jTextField3");
        o_percolation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_percolationActionPerformed(evt);
            }
        });
        o_percolation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                o_percolationFocusLost(evt);
            }
        });

        jLabel2.setText("Max packing fraction:");

        o_maxPack.setText("jTextField2");
        o_maxPack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_maxPackActionPerformed(evt);
            }
        });
        o_maxPack.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                o_maxPackFocusLost(evt);
            }
        });

        jLabel12.setText("Volume increment function:");

        o_volumeFunction.setModel(new DefaultComboBoxModel<Yodel.VolumeIncrementFunction>(Yodel.VolumeIncrementFunction.values()));
        o_volumeFunction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_volumeFunctionActionPerformed(evt);
            }
        });

        jLabel5.setText("-");

        jLabel13.setText("-");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Curvature radius of contact"));

        o_curvatureGroup.add(o_radiusManual);
        o_radiusManual.setText("Manual:");
        o_radiusManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_radiusManualActionPerformed(evt);
            }
        });

        o_contactRadius.setText("jTextField1");
        o_contactRadius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_contactRadiusActionPerformed(evt);
            }
        });
        o_contactRadius.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                o_contactRadiusFocusLost(evt);
            }
        });

        o_curvatureGroup.add(o_radiusHarmonic);
        o_radiusHarmonic.setText("Harmonic radius:");
        o_radiusHarmonic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_radiusHarmonicActionPerformed(evt);
            }
        });

        jLabel8.setText("nm");

        o_harmRadius.setText("jLabel19");

        jLabel20.setText("nm");

        o_b_tilda_bug.setText("Factor 1000 (reproduce potential bug in original YODEL b~)");
        o_b_tilda_bug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_b_tilda_bugActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(o_radiusHarmonic)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(o_harmRadius)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel20))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(o_radiusManual)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(o_contactRadius, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel8))
                    .add(o_b_tilda_bug))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(o_radiusManual)
                    .add(o_contactRadius, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel8))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(o_radiusHarmonic)
                    .add(o_harmRadius)
                    .add(jLabel20))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(o_b_tilda_bug)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Max interparticle force parameter"));

        o_forceGroup.add(o_forceAutomatic);
        o_forceAutomatic.setText("Automatic:");
        o_forceAutomatic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_forceAutomaticActionPerformed(evt);
            }
        });

        o_forceGroup.add(o_forceManual);
        o_forceManual.setText("Manual:");
        o_forceManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_forceManualActionPerformed(evt);
            }
        });

        jLabel3.setText("Hamaker constant:");

        jLabel4.setText("Minimum separation:");

        o_manualSeparation.setText("jTextField4");
        o_manualSeparation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                o_manualSeparationFocusLost(evt);
            }
        });
        o_manualSeparation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_manualSeparationActionPerformed(evt);
            }
        });

        o_manualHamaker.setText("jTextField5");
        o_manualHamaker.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                o_manualHamakerFocusLost(evt);
            }
        });
        o_manualHamaker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_manualHamakerActionPerformed(evt);
            }
        });

        jLabel9.setText("J");

        jLabel10.setText("nm");

        jLabel6.setText("Hamaker constant:");

        jLabel7.setText("Minimum separation:");

        o_autoHamaker.setText("jLabel11");

        o_autoSeparation.setText("jLabel14");

        jLabel17.setText("J");

        jLabel18.setText("nm");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(o_forceAutomatic)
                    .add(o_forceManual))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel4)
                    .add(jLabel3)
                    .add(jLabel6)
                    .add(jLabel7))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(o_manualSeparation, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel10))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(o_manualHamaker, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(o_autoHamaker)
                            .add(o_autoSeparation))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel18)
                            .add(jLabel17)
                            .add(jLabel9))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(o_forceAutomatic)
                    .add(jLabel6)
                    .add(o_autoHamaker)
                    .add(jLabel17))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(o_autoSeparation)
                    .add(jLabel18))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(o_forceManual)
                    .add(jLabel3)
                    .add(o_manualHamaker, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel9))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(o_manualSeparation, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel10))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel15.setText("Model:");

        o_model.setModel(new DefaultComboBoxModel<Yodel.Model>(Yodel.Model.values()));
        o_model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_modelActionPerformed(evt);
            }
        });

        jLabel16.setText("Particle volume fractions:");

        o_volFracSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                o_volFracSliderStateChanged(evt);
            }
        });

        o_volFrac1.setText("jLabel17");

        o_volFrac2.setText("jLabel18");

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jPanel3Layout.createSequentialGroup()
                                .add(jLabel15)
                                .add(145, 145, 145)
                                .add(o_model, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .add(jPanel3Layout.createSequentialGroup()
                                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel2)
                                    .add(jLabel1))
                                .add(50, 50, 50)
                                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(o_maxPack)
                                    .add(o_percolation, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 99, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel13)
                                    .add(jLabel5)))
                            .add(jPanel3Layout.createSequentialGroup()
                                .add(jLabel12)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(o_volumeFunction, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 251, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(0, 0, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                        .add(jLabel16)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel3Layout.createSequentialGroup()
                                .add(o_volFrac1)
                                .add(145, 145, 145)
                                .add(o_volFrac2))
                            .add(o_volFracSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 251, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel15)
                    .add(o_model, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(o_percolation, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(o_maxPack, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel13))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel12)
                    .add(o_volumeFunction, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel16)
                    .add(o_volFrac1)
                    .add(o_volFrac2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(o_volFracSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(o_paintPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(o_cancelButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(o_okButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(o_paintPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(o_okButton)
                    .add(o_cancelButton))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void o_radiusManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_radiusManualActionPerformed
        m_editedSerie.getYodel().setHarmonicCurvature(false);
        o_contactRadius.setEnabled(true);
        updatePlot();
    }//GEN-LAST:event_o_radiusManualActionPerformed

    private void o_forceAutomaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_forceAutomaticActionPerformed
        m_editedSerie.getYodel().setAutoAttractiveForce(true);
        o_manualHamaker.setEnabled(false);
        o_manualSeparation.setEnabled(false);
        updatePlot();
    }//GEN-LAST:event_o_forceAutomaticActionPerformed

    private void o_forceManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_forceManualActionPerformed
        m_editedSerie.getYodel().setAutoAttractiveForce(false);
        o_manualHamaker.setEnabled(true);
        o_manualSeparation.setEnabled(true);
        updatePlot();
    }//GEN-LAST:event_o_forceManualActionPerformed

    private void o_okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_okButtonActionPerformed
        setVisible(false);
        m_editedSerie = null;
        m_saveSerie = null;
    }//GEN-LAST:event_o_okButtonActionPerformed

    private void o_radiusHarmonicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_radiusHarmonicActionPerformed
        m_editedSerie.getYodel().setHarmonicCurvature(true);
        o_contactRadius.setEnabled(false);
        updatePlot();
    }//GEN-LAST:event_o_radiusHarmonicActionPerformed

    private void o_manualSeparationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_manualSeparationActionPerformed
        m_editedSerie.getYodel().setManualAttractiveSeparation(Utils.StringToDouble(o_manualSeparation.getText()) * 1E-9);
        updatePlot();
    }//GEN-LAST:event_o_manualSeparationActionPerformed

    private void o_manualSeparationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_o_manualSeparationFocusLost
        m_editedSerie.getYodel().setManualAttractiveSeparation(Utils.StringToDouble(o_manualSeparation.getText()) * 1E-9);
        updatePlot();
    }//GEN-LAST:event_o_manualSeparationFocusLost

    private void o_manualHamakerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_manualHamakerActionPerformed
        m_editedSerie.getYodel().setManualAttractiveHamaker(Utils.StringToDouble(o_manualHamaker.getText()));
        updatePlot();
    }//GEN-LAST:event_o_manualHamakerActionPerformed

    private void o_manualHamakerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_o_manualHamakerFocusLost
        m_editedSerie.getYodel().setManualAttractiveHamaker(Utils.StringToDouble(o_manualHamaker.getText()));
        updatePlot();
    }//GEN-LAST:event_o_manualHamakerFocusLost

    private void o_cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_cancelButtonActionPerformed
        m_editedSerie = m_saveSerie;
        setVisible(false);
        m_editedSerie = null;
        m_saveSerie = null;
    }//GEN-LAST:event_o_cancelButtonActionPerformed

    private void o_percolationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_percolationActionPerformed
        m_editedSerie.getYodel().setPercolationTreshold(Utils.StringToDouble(o_percolation.getText()));
        updatePlot();
    }//GEN-LAST:event_o_percolationActionPerformed

    private void o_percolationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_o_percolationFocusLost
        m_editedSerie.getYodel().setPercolationTreshold(Utils.StringToDouble(o_percolation.getText()));
        updatePlot();
    }//GEN-LAST:event_o_percolationFocusLost

    private void o_maxPackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_maxPackActionPerformed
        m_editedSerie.getYodel().setMaxPackingFraction(Utils.StringToDouble(o_maxPack.getText()));
        updatePlot();
    }//GEN-LAST:event_o_maxPackActionPerformed

    private void o_maxPackFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_o_maxPackFocusLost
        m_editedSerie.getYodel().setMaxPackingFraction(Utils.StringToDouble(o_maxPack.getText()));
        updatePlot();
    }//GEN-LAST:event_o_maxPackFocusLost

    private void o_volumeFunctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_volumeFunctionActionPerformed
        if (m_editedSerie != null) {
            m_editedSerie.getYodel().setVolumeIncrementFunction(o_volumeFunction.getItemAt(o_volumeFunction.getSelectedIndex()));
        }
        updatePlot();
    }//GEN-LAST:event_o_volumeFunctionActionPerformed

    private void o_contactRadiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_contactRadiusActionPerformed
        m_editedSerie.getYodel().setCurvatureRadius(Utils.StringToDouble(o_contactRadius.getText()) * 1E-9);
        updatePlot();
    }//GEN-LAST:event_o_contactRadiusActionPerformed

    private void o_contactRadiusFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_o_contactRadiusFocusLost
        m_editedSerie.getYodel().setCurvatureRadius(Utils.StringToDouble(o_contactRadius.getText()) * 1E-9);
        updatePlot();
    }//GEN-LAST:event_o_contactRadiusFocusLost

    private void o_modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_modelActionPerformed
        if (m_editedSerie != null) {
            m_editedSerie.getYodel().setModel(o_model.getItemAt(o_model.getSelectedIndex()));
        }
        updatePlot();
    }//GEN-LAST:event_o_modelActionPerformed

    private void o_volFracSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_o_volFracSliderStateChanged
        o_volFrac1.setText(new DecimalFormat("0.00").format(m_editedSerie.getYodel().getParticle1VolumeFraction()));
        o_volFrac2.setText(new DecimalFormat("0.00").format(m_editedSerie.getYodel().getParticle2VolumeFraction()));
        m_editedSerie.getYodel().setParticle1VolumeFraction(1.0 - o_volFracSlider.getValue() / 100.0);
        updatePlot();
    }//GEN-LAST:event_o_volFracSliderStateChanged

    private void o_b_tilda_bugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_b_tilda_bugActionPerformed
        m_editedSerie.getYodel().setBTildaBug(o_b_tilda_bug.isSelected());
        updatePlot();
    }//GEN-LAST:event_o_b_tilda_bugActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel o_autoHamaker;
    private javax.swing.JLabel o_autoSeparation;
    private javax.swing.JCheckBox o_b_tilda_bug;
    private javax.swing.JButton o_cancelButton;
    private javax.swing.JTextField o_contactRadius;
    private javax.swing.ButtonGroup o_curvatureGroup;
    private javax.swing.JRadioButton o_forceAutomatic;
    private javax.swing.ButtonGroup o_forceGroup;
    private javax.swing.JRadioButton o_forceManual;
    private javax.swing.JLabel o_harmRadius;
    private javax.swing.JTextField o_manualHamaker;
    private javax.swing.JTextField o_manualSeparation;
    private javax.swing.JTextField o_maxPack;
    private javax.swing.JComboBox<Yodel.Model> o_model;
    private javax.swing.JButton o_okButton;
    private javax.swing.JPanel o_paintPanel;
    private javax.swing.JTextField o_percolation;
    private javax.swing.JRadioButton o_radiusHarmonic;
    private javax.swing.JRadioButton o_radiusManual;
    private javax.swing.JLabel o_volFrac1;
    private javax.swing.JLabel o_volFrac2;
    private javax.swing.JSlider o_volFracSlider;
    private javax.swing.JComboBox<Yodel.VolumeIncrementFunction> o_volumeFunction;
    // End of variables declaration//GEN-END:variables

    private final org.jfree.data.xy.XYSeriesCollection m_yodelPlotData;
    private org.jfree.chart.plot.Crosshair m_xCrosshair, m_yCrosshair;

    private void updatePlot() {
        if (m_editedSerie != null) {
            //m_editedSerie.getYodel().printParams();

            Yodel yodel = m_editedSerie.getYodel();

            m_yodelPlotData.removeAllSeries();
            XYSeries newSerie = new XYSeries("");

            final int kNumPoints = 100;
            double min = yodel.getPercolationTreshold();
            double max = yodel.getMaxPackingFraction();
            double stepSize = (max - min) / ((double) kNumPoints);

            for (int point = 0; point < kNumPoints; point++) {
                double volFrac = min + point * stepSize;
                double yieldStress = yodel.yieldStress(m_editedSerie, volFrac);

                //System.out.println(String.valueOf(volFrac) + ", " + String.valueOf(yieldStress));
                newSerie.add(volFrac, yieldStress);
            }

            m_yodelPlotData.addSeries(newSerie);

            o_paintPanel.repaint();
        }
    }

    private JPanel createPlotPanel() {
        JFreeChart chart = org.jfree.chart.ChartFactory.createXYLineChart(
                null, //title
                "Volume fraction (-)", //x axis label
                "Yield stress (Pa)", //y axis label
                m_yodelPlotData, //data 
                org.jfree.chart.plot.PlotOrientation.VERTICAL, //orientation
                false, //legend
                true, //tootips
                false //URLs
        );
        chart.getPlot().setBackgroundPaint(Color.white);
        
        org.jfree.chart.ChartPanel panel = new org.jfree.chart.ChartPanel(chart,
                400, //width
                200, //height
                50, //min width
                50, //min height
                1000, //max width
                1000, //max height
                false, //buffer
                false, //properties
                false, //save
                false, //print
                false, //zoom
                false); //tooltips

        //create the crosshair
        m_xCrosshair = new org.jfree.chart.plot.Crosshair(Double.NaN, Color.GRAY, new BasicStroke(0f));
        m_yCrosshair = new org.jfree.chart.plot.Crosshair(Double.NaN, Color.GRAY, new BasicStroke(0f));
        m_xCrosshair.setLabelVisible(true);
        m_yCrosshair.setLabelVisible(true);
        
        org.jfree.chart.panel.CrosshairOverlay crosshairs = new org.jfree.chart.panel.CrosshairOverlay();
        crosshairs.addDomainCrosshair(m_xCrosshair); //x axis
        crosshairs.addRangeCrosshair(m_yCrosshair); //y axis
        panel.addOverlay(crosshairs);

        panel.addChartMouseListener(this);

        return panel;
    }    

    @Override
    public void chartMouseClicked(ChartMouseEvent event) {
//ignore
    }

    @Override
    public void chartMouseMoved(ChartMouseEvent event) {
        
        org.jfree.chart.ChartPanel panel = (org.jfree.chart.ChartPanel)o_paintPanel;
        
        Rectangle2D dataArea = panel.getScreenDataArea();
        JFreeChart chart = event.getChart();
        org.jfree.chart.plot.XYPlot plot = (org.jfree.chart.plot.XYPlot) chart.getPlot();
        org.jfree.chart.axis.ValueAxis xAxis = plot.getDomainAxis();
        double x = xAxis.java2DToValue(event.getTrigger().getX(), dataArea, org.jfree.ui.RectangleEdge.BOTTOM);
        double y = interpolate(m_yodelPlotData.getSeries(0), x);
        m_xCrosshair.setValue(x);
        m_yCrosshair.setValue(y);
    }
    
    private double interpolate(XYSeries s, double x)
    {
        if (x <= s.getMinX())
        {
            return s.getY(0).doubleValue();
        }
        if (x >= s.getMaxX())
        {
            return s.getY(s.getItemCount()-1).doubleValue();
        }
        List<?> items = s.getItems();
        for (int i=0; i<items.size()-1; i++)
        {
            org.jfree.data.xy.XYDataItem i0 = (org.jfree.data.xy.XYDataItem) items.get(i);
            org.jfree.data.xy.XYDataItem i1 = (org.jfree.data.xy.XYDataItem) items.get(i+1);
            double x0 = i0.getXValue();
            double y0 = i0.getYValue();
            double x1 = i1.getXValue();
            double y1 = i1.getYValue();

            if (x >= x0 && x <= x1)
            {
                double d = x - x0;
                double a = d / (x1-x0);
                double y = y0 + a * (y1 - y0);
                return y;
            }
        }
        // Should never happen
        return 0;
    }
}
