/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hamaker2.models.misc;

import hamaker2.Utils;
import hamaker2.models.Oscillator;
import java.awt.event.ActionEvent;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.AbstractTableModel;

/**
 * More dialog for the Lifshitz magnetic model
 * @author uli
 */
public class Misc_LifshitzMagneticDialog extends javax.swing.JDialog implements ListSelectionListener, TableModelListener {

    Misc_LifshitzMagnetic m_model, m_saveModel;
    
    /**
     * Creates new form BuildLifshitz
     * @param model Model to be displayed
     */
    public Misc_LifshitzMagneticDialog(Misc_LifshitzMagnetic model) {
        
        super((java.awt.Frame)null, true);
        
        m_model = model;
        m_saveModel = m_model.duplicate();
        
        initComponents();
        
        rootPane.setDefaultButton(o_okButton);
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ESCAPE"), "cancelAction");
        getRootPane().getActionMap().put("cancelAction", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                o_cancelButtonActionPerformed(ae);
            }
        });
        
        o_magTableP1.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
        o_magTableP2.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
        o_magTableM.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
        
        updateDeleteButtons();
        updateMagHam();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        o_okButton = new javax.swing.JButton();
        o_cancelButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        o_mag1Delete = new javax.swing.JButton();
        o_mag1Add = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        o_magTableP2 = new javax.swing.JTable();
        o_mag2Delete = new javax.swing.JButton();
        o_mag2Add = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        o_magMatsubara = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        o_magS = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        o_magTableP1 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        o_magTableM = new javax.swing.JTable();
        o_magMAdd = new javax.swing.JButton();
        o_magMDelete = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        o_magTemp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        o_magHam = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lifshitz with Magnetic");
        setModal(true);

        o_okButton.setText("OK");
        o_okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_okButtonActionPerformed(evt);
            }
        });

        o_cancelButton.setText("Cancel");
        o_cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_cancelButtonActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Magnetic response function"));

        o_mag1Delete.setText("Delete");
        o_mag1Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_mag1DeleteActionPerformed(evt);
            }
        });

        o_mag1Add.setText("Add");
        o_mag1Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_mag1AddActionPerformed(evt);
            }
        });

        jLabel12.setText("Particle 1");

        o_magTableP2.setModel(new ResponseFunctionTableModel(m_model.magFunction(2)));
        o_magTableP2.getSelectionModel().addListSelectionListener(this);
        o_magTableP2.getModel().addTableModelListener(this);
        jScrollPane2.setViewportView(o_magTableP2);

        o_mag2Delete.setText("Delete");
        o_mag2Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_mag2DeleteActionPerformed(evt);
            }
        });

        o_mag2Add.setText("Add");
        o_mag2Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_mag2AddActionPerformed(evt);
            }
        });

        jLabel2.setText("(-)");

        o_magMatsubara.setText(String.valueOf(m_model.magMatsubaraMax()));
        o_magMatsubara.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                handle();
            }
            public void removeUpdate(DocumentEvent e) {
                handle();
            }
            public void insertUpdate(DocumentEvent e) {
                handle();
            }
            public void handle() {
                if (!o_magMatsubara.getText().equals("")) {
                    m_model.setMagMatsubaraMax(Utils.StringToInt(o_magMatsubara.getText()));
                    updateMagHam();
                }
            }
        });

        jLabel7.setText("Max power:");

        jLabel13.setText("Particle 2");

        o_magS.setText(String.valueOf(m_model.magSMax()));
        o_magS.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                handle();
            }
            public void removeUpdate(DocumentEvent e) {
                handle();
            }
            public void insertUpdate(DocumentEvent e) {
                handle();
            }
            public void handle() {
                if (!o_magS.getText().equals("")) {
                    m_model.setMagSMax(Utils.StringToInt(o_magS.getText()));
                    updateMagHam();
                }
            }
        });

        jLabel1.setText("Matsubara steps:");

        jLabel8.setText("(-)");

        o_magTableP1.setModel(new ResponseFunctionTableModel(m_model.magFunction(1)));
        o_magTableP1.getSelectionModel().addListSelectionListener(this);
        o_magTableP1.getModel().addTableModelListener(this);
        jScrollPane3.setViewportView(o_magTableP1);

        jLabel17.setText("Medium");

        o_magTableM.setModel(new ResponseFunctionTableModel(m_model.magFunction(0)));
        o_magTableM.getSelectionModel().addListSelectionListener(this);
        o_magTableM.getModel().addTableModelListener(this);
        jScrollPane4.setViewportView(o_magTableM);

        o_magMAdd.setText("Add");
        o_magMAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_magMAddActionPerformed(evt);
            }
        });

        o_magMDelete.setText("Delete");
        o_magMDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_magMDeleteActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Magnetic Hamaker constant contribution"));

        jLabel3.setText("Temperature:");

        o_magTemp.setText(String.valueOf(m_model.magTemp()));
        o_magTemp.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                handle();
            }
            public void removeUpdate(DocumentEvent e) {
                handle();
            }
            public void insertUpdate(DocumentEvent e) {
                handle();
            }
            public void handle() {
                if (!o_magTemp.getText().equals("")) {
                    m_model.setMagTemp(Utils.StringToDouble(o_magTemp.getText()));
                    updateMagHam();
                }
            }
        });

        jLabel11.setText("K");

        jLabel19.setText("Result:");

        o_magHam.setText("value");

        jLabel5.setText("J");

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(o_magTemp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel11)
                .add(50, 50, 50)
                .add(jLabel19)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(o_magHam)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel5)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel19)
                        .add(o_magHam)
                        .add(jLabel5))
                    .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel3)
                        .add(o_magTemp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel11)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(o_mag1Add)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(o_mag1Delete))
                            .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 177, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel12))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(o_mag2Add)
                                .add(18, 18, 18)
                                .add(o_mag2Delete))
                            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 165, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel13))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jScrollPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 165, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel17)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(o_magMAdd)
                                .add(18, 18, 18)
                                .add(o_magMDelete))))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(jLabel7)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(o_magS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel8))
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(jLabel1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(o_magMatsubara, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel2)))
                        .add(47, 47, 47)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(new java.awt.Component[] {jScrollPane2, jScrollPane3, jScrollPane4}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel2Layout.linkSize(new java.awt.Component[] {o_magMatsubara, o_magS}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(o_magMatsubara, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel7)
                            .add(o_magS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel8))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel12)
                            .add(jLabel13))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 190, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(0, 0, Short.MAX_VALUE))))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                        .add(40, 40, 40)
                        .add(jLabel17)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 190, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(o_mag1Add)
                    .add(o_mag1Delete)
                    .add(o_mag2Add)
                    .add(o_mag2Delete)
                    .add(o_magMAdd)
                    .add(o_magMDelete))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(new java.awt.Component[] {jScrollPane2, jScrollPane3, jScrollPane4}, org.jdesktop.layout.GroupLayout.VERTICAL);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(o_cancelButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(o_okButton))
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(0, 12, Short.MAX_VALUE)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(o_okButton)
                    .add(o_cancelButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void o_mag1AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_mag1AddActionPerformed
        m_model.magFunction(1).add(new Oscillator(0, 1));
        o_magTableP1.updateUI();
        updateMagHam();
    }//GEN-LAST:event_o_mag1AddActionPerformed

    private void o_mag1DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_mag1DeleteActionPerformed
        m_model.magFunction(1).remove(o_magTableP1.getSelectedRow());
        o_magTableP1.updateUI();
        updateDeleteButtons();
        updateMagHam();
    }//GEN-LAST:event_o_mag1DeleteActionPerformed

    private void o_cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_cancelButtonActionPerformed
        m_model.valuesFromModel(m_saveModel);
        this.setVisible(false);
        m_model = null;
        m_saveModel = null;
    }//GEN-LAST:event_o_cancelButtonActionPerformed

    private void o_okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_okButtonActionPerformed
        this.setVisible(false);
        m_model = null;
        m_saveModel = null;
    }//GEN-LAST:event_o_okButtonActionPerformed

    private void o_mag2AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_mag2AddActionPerformed
        m_model.magFunction(2).add(new Oscillator(0, 1));
        o_magTableP2.updateUI();
        updateMagHam();
    }//GEN-LAST:event_o_mag2AddActionPerformed

    private void o_mag2DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_mag2DeleteActionPerformed
        m_model.magFunction(2).remove(o_magTableP2.getSelectedRow());
        o_magTableP2.updateUI();
        updateDeleteButtons();
        updateMagHam();
    }//GEN-LAST:event_o_mag2DeleteActionPerformed

    private void o_magMAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_magMAddActionPerformed
        m_model.magFunction(0).add(new Oscillator(0, 1));
        o_magTableM.updateUI();
        updateMagHam();
    }//GEN-LAST:event_o_magMAddActionPerformed

    private void o_magMDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_magMDeleteActionPerformed
        m_model.magFunction(0).remove(o_magTableM.getSelectedRow());
        o_magTableM.updateUI();
        updateDeleteButtons();
        updateMagHam();
    }//GEN-LAST:event_o_magMDeleteActionPerformed
    
    @Override
    public void valueChanged(ListSelectionEvent e) {
        updateDeleteButtons();
    }

    private void updateDeleteButtons() {
        o_mag1Delete.setEnabled(o_magTableP1.getRowCount() > 0 && o_magTableP1.getSelectedRowCount() > 0 && o_magTableP1.getSelectedRow() < o_magTableP1.getRowCount());
        o_mag2Delete.setEnabled(o_magTableP2.getRowCount() > 0 && o_magTableP2.getSelectedRowCount() > 0 && o_magTableP2.getSelectedRow() < o_magTableP2.getRowCount());
        o_magMDelete.setEnabled(o_magTableM.getRowCount()  > 0 && o_magTableM.getSelectedRowCount()  > 0 && o_magTableM.getSelectedRow()  < o_magTableM.getRowCount());
    }                                             
    
    private void updateMagHam() {
        o_magHam.setText(new DecimalFormat("0.0000E0").format(m_model.lifshitzHamakerConstant(m_model.magTemp())));
    }

    @Override
    public void tableChanged(TableModelEvent e) {
        updateMagHam();
    }
    
    private class ResponseFunctionTableModel extends AbstractTableModel {

        ArrayList<Oscillator> m_data;
        
        public ResponseFunctionTableModel(ArrayList<Oscillator> data) {
            m_data = data;
        }
        
        @Override
        public int getRowCount() {
            return m_data.size();
        }

        @Override
        public int getColumnCount() {
            return 2;
        }
        
        @Override
        public String getColumnName(int columnIndex) {
            if (columnIndex == 0) {
                return "C (-)";
            } else if (columnIndex == 1) {
                return "omega (THz)";
            } else {
                System.out.println("ResponseFunctionTableModel error: unknown column index");
                return "";
            }
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            if (columnIndex == 0) {
                return String.valueOf(m_data.get(rowIndex).getStrength());
            } else if (columnIndex == 1) {
                return String.valueOf(m_data.get(rowIndex).getFrequencyTHz());
            } else {
                System.out.println("ResponseFunctionTableModel error: unknown column index");
                return null;
            }
        }
        
        @Override
        public boolean isCellEditable(int row, int column) {
            return true;
        }
        
        @Override
        public void setValueAt(Object value, int rowIndex, int columnIndex) {
            if (columnIndex == 0) {
                m_data.get(rowIndex).setStrength(Utils.StringToDouble((String)value));
            } else if (columnIndex == 1) {
                m_data.get(rowIndex).setFrequencyTHz(Utils.StringToDouble((String)value));
            } else {
                System.out.println("ResponseFunctionTableModel error: unknown column index");
            }
            
            this.fireTableDataChanged();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton o_cancelButton;
    private javax.swing.JButton o_mag1Add;
    private javax.swing.JButton o_mag1Delete;
    private javax.swing.JButton o_mag2Add;
    private javax.swing.JButton o_mag2Delete;
    private javax.swing.JLabel o_magHam;
    private javax.swing.JButton o_magMAdd;
    private javax.swing.JButton o_magMDelete;
    private javax.swing.JTextField o_magMatsubara;
    private javax.swing.JTextField o_magS;
    private javax.swing.JTable o_magTableM;
    private javax.swing.JTable o_magTableP1;
    private javax.swing.JTable o_magTableP2;
    private javax.swing.JTextField o_magTemp;
    private javax.swing.JButton o_okButton;
    // End of variables declaration//GEN-END:variables
}
