/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hamaker2.models.dispersion;

import hamaker2.Utils;
import hamaker2.models.Oscillator;
import java.awt.event.ActionEvent;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.AbstractTableModel;

/**
 * More dialog for the Lifshitz dispersion model
 * @author uli
 */
public class Dispersion_LifshitzDialog extends javax.swing.JDialog implements ListSelectionListener, TableModelListener {

    Dispersion_Lifshitz m_model, m_saveModel;
    
    /**
     * Creates new form BuildLifshitz
     * @param model Model to be displayed
     */
    public Dispersion_LifshitzDialog(Dispersion_Lifshitz model) {
        
        super((java.awt.Frame)null, true);
        
        m_model = model;
        m_saveModel = m_model.duplicate();
        
        initComponents();
        
        rootPane.setDefaultButton(o_okButton);
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ESCAPE"), "cancelAction");
        getRootPane().getActionMap().put("cancelAction", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                o_cancelButtonActionPerformed(ae);
            }
        });

        o_dielTableP1.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
        o_dielTableP2.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
        o_dielTableM.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
                
        updateDeleteButtons();
        updateDielHam();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        o_okButton = new javax.swing.JButton();
        o_cancelButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        o_diel1Delete = new javax.swing.JButton();
        o_diel1Add = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        o_dielTableP2 = new javax.swing.JTable();
        o_diel2Delete = new javax.swing.JButton();
        o_diel2Add = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        o_dielMatsubara = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        o_dielS = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        o_dielTableP1 = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        o_dielTableM = new javax.swing.JTable();
        o_dielMAdd = new javax.swing.JButton();
        o_dielMDelete = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        o_dielTemp = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        o_dielHam = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lifshitz with Magnetic");
        setModal(true);

        o_okButton.setText("OK");
        o_okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_okButtonActionPerformed(evt);
            }
        });

        o_cancelButton.setText("Cancel");
        o_cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_cancelButtonActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Dielectric response function"));

        o_diel1Delete.setText("Delete");
        o_diel1Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_diel1DeleteActionPerformed(evt);
            }
        });

        o_diel1Add.setText("Add");
        o_diel1Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_diel1AddActionPerformed(evt);
            }
        });

        jLabel21.setText("Particle 1");

        o_dielTableP2.setModel(new ResponseFunctionTableModel(m_model.dielFunction(2)));
        o_dielTableP2.getSelectionModel().addListSelectionListener(this);
        o_dielTableP2.getModel().addTableModelListener(this);
        jScrollPane7.setViewportView(o_dielTableP2);

        o_diel2Delete.setText("Delete");
        o_diel2Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_diel2DeleteActionPerformed(evt);
            }
        });

        o_diel2Add.setText("Add");
        o_diel2Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_diel2AddActionPerformed(evt);
            }
        });

        jLabel22.setText("(-)");

        o_dielMatsubara.setText(String.valueOf(m_model.dielMatsubaraMax()));
        o_dielMatsubara.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                handle();
            }
            public void removeUpdate(DocumentEvent e) {
                handle();
            }
            public void insertUpdate(DocumentEvent e) {
                handle();
            }
            public void handle() {
                if (!o_dielMatsubara.getText().equals("")) {
                    m_model.setDielMatsubaraMax(Utils.StringToInt(o_dielMatsubara.getText()));
                    updateDielHam();
                }
            }
        });

        jLabel23.setText("Max power:");

        jLabel24.setText("Particle 2");

        o_dielS.setText(String.valueOf(m_model.dielSMax()));
        o_dielS.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                handle();
            }
            public void removeUpdate(DocumentEvent e) {
                handle();
            }
            public void insertUpdate(DocumentEvent e) {
                handle();
            }
            public void handle() {
                if (!o_dielS.getText().equals("")) {
                    m_model.setDielSMax(Utils.StringToInt(o_dielS.getText()));
                    updateDielHam();
                }
            }
        });

        jLabel25.setText("Matsubara steps:");

        jLabel26.setText("(-)");

        o_dielTableP1.setModel(new ResponseFunctionTableModel(m_model.dielFunction(1)));
        o_dielTableP1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        o_dielTableP1.getSelectionModel().addListSelectionListener(this);
        o_dielTableP1.getModel().addTableModelListener(this);
        jScrollPane8.setViewportView(o_dielTableP1);

        jLabel27.setText("Medium");

        o_dielTableM.setModel(new ResponseFunctionTableModel(m_model.dielFunction(0)));
        o_dielTableM.getSelectionModel().addListSelectionListener(this);
        o_dielTableM.getModel().addTableModelListener(this);
        jScrollPane9.setViewportView(o_dielTableM);

        o_dielMAdd.setText("Add");
        o_dielMAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_dielMAddActionPerformed(evt);
            }
        });

        o_dielMDelete.setText("Delete");
        o_dielMDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_dielMDeleteActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Dielectric Hamaker constant contribution"));

        jLabel28.setText("Temperature:");

        o_dielTemp.setText(String.valueOf(m_model.dielTemp()));
        o_dielTemp.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                handle();
            }
            public void removeUpdate(DocumentEvent e) {
                handle();
            }
            public void insertUpdate(DocumentEvent e) {
                handle();
            }
            public void handle() {
                if (!o_dielTemp.getText().equals("")) {
                    m_model.setDielTemp(Utils.StringToDouble(o_dielTemp.getText()));
                    updateDielHam();
                }
            }
        });

        jLabel30.setText("K");

        jLabel32.setText("Result:");

        o_dielHam.setText("value");

        jLabel4.setText("J");

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel28)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(o_dielTemp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel30)
                .add(47, 47, 47)
                .add(jLabel32)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(o_dielHam)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel4)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel32)
                        .add(o_dielHam)
                        .add(jLabel4))
                    .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel28)
                        .add(o_dielTemp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel30)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jPanel4Layout.createSequentialGroup()
                                .add(o_diel1Add)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(o_diel1Delete))
                            .add(jScrollPane8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 177, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel21))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel4Layout.createSequentialGroup()
                                .add(o_diel2Add)
                                .add(18, 18, 18)
                                .add(o_diel2Delete))
                            .add(jScrollPane7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 165, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel24))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jScrollPane9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 165, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel27)
                            .add(jPanel4Layout.createSequentialGroup()
                                .add(o_dielMAdd)
                                .add(18, 18, 18)
                                .add(o_dielMDelete))))
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(jPanel4Layout.createSequentialGroup()
                                .add(jLabel23)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(o_dielS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel26))
                            .add(jPanel4Layout.createSequentialGroup()
                                .add(jLabel25)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(o_dielMatsubara, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel22)))
                        .add(47, 47, 47)))
                .addContainerGap())
        );

        jPanel4Layout.linkSize(new java.awt.Component[] {jScrollPane7, jScrollPane8, jScrollPane9}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel25)
                    .add(o_dielMatsubara, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel22))
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel23)
                            .add(o_dielS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel26))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel21)
                            .add(jLabel24))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jScrollPane8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .add(jPanel4Layout.createSequentialGroup()
                                .add(jScrollPane7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 190, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(0, 0, Short.MAX_VALUE))))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createSequentialGroup()
                        .add(40, 40, 40)
                        .add(jLabel27)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPane9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 190, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(o_diel1Add)
                    .add(o_diel1Delete)
                    .add(o_diel2Add)
                    .add(o_diel2Delete)
                    .add(o_dielMAdd)
                    .add(o_dielMDelete))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(new java.awt.Component[] {jScrollPane7, jScrollPane8, jScrollPane9}, org.jdesktop.layout.GroupLayout.VERTICAL);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(o_cancelButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(o_okButton))
                    .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(o_okButton)
                    .add(o_cancelButton))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void o_cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_cancelButtonActionPerformed
        m_model.valuesFromModel(m_saveModel);
        this.setVisible(false);
        m_model = null;
        m_saveModel = null;
    }//GEN-LAST:event_o_cancelButtonActionPerformed

    private void o_okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_okButtonActionPerformed
        this.setVisible(false);
        m_model = null;
        m_saveModel = null;
    }//GEN-LAST:event_o_okButtonActionPerformed

    private void o_diel1DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_diel1DeleteActionPerformed
        m_model.dielFunction(1).remove(o_dielTableP1.getSelectedRow());
        o_dielTableP1.updateUI();
        updateDeleteButtons();
        updateDielHam();
    }//GEN-LAST:event_o_diel1DeleteActionPerformed

    private void o_diel1AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_diel1AddActionPerformed
        m_model.dielFunction(1).add(new Oscillator(0, 1));
        o_dielTableP1.updateUI();
        updateDielHam();
    }//GEN-LAST:event_o_diel1AddActionPerformed

    private void o_diel2DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_diel2DeleteActionPerformed
        m_model.dielFunction(2).remove(o_dielTableP2.getSelectedRow());
        o_dielTableP2.updateUI();
        updateDeleteButtons();
        updateDielHam();
    }//GEN-LAST:event_o_diel2DeleteActionPerformed

    private void o_diel2AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_diel2AddActionPerformed
        m_model.dielFunction(2).add(new Oscillator(0, 1));
        o_dielTableP2.updateUI();
        updateDielHam();
    }//GEN-LAST:event_o_diel2AddActionPerformed

    private void o_dielMAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_dielMAddActionPerformed
        m_model.dielFunction(0).add(new Oscillator(0, 1));
        o_dielTableM.updateUI();
        updateDielHam();
    }//GEN-LAST:event_o_dielMAddActionPerformed

    private void o_dielMDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_dielMDeleteActionPerformed
        m_model.dielFunction(0).remove(o_dielTableM.getSelectedRow());
        o_dielTableM.updateUI();
        updateDeleteButtons();
        updateDielHam();
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        updateDeleteButtons();
    }

    private void updateDeleteButtons() {
        o_diel1Delete.setEnabled(o_dielTableP1.getRowCount() > 0 && o_dielTableP1.getSelectedRowCount() > 0 && o_dielTableP1.getSelectedRow() < o_dielTableP1.getRowCount());
        o_diel2Delete.setEnabled(o_dielTableP2.getRowCount() > 0 && o_dielTableP2.getSelectedRowCount() > 0 && o_dielTableP2.getSelectedRow() < o_dielTableP2.getRowCount());
        o_dielMDelete.setEnabled(o_dielTableM.getRowCount()  > 0 && o_dielTableM.getSelectedRowCount()  > 0 && o_dielTableM.getSelectedRow()  < o_dielTableM.getRowCount());
    }//GEN-LAST:event_o_dielMDeleteActionPerformed

    
    private void updateDielHam() {
        o_dielHam.setText(new DecimalFormat("0.0000E0").format(m_model.lifshitzHamakerConstant(m_model.dielTemp())));
    }
    
    @Override
    public void tableChanged(TableModelEvent e) {
        updateDielHam();
    }
    
    private class ResponseFunctionTableModel extends AbstractTableModel {

        ArrayList<Oscillator> m_data;
        
        public ResponseFunctionTableModel(ArrayList<Oscillator> data) {
            m_data = data;
        }
        
        @Override
        public int getRowCount() {
            return m_data.size();
        }

        @Override
        public int getColumnCount() {
            return 2;
        }
        
        @Override
        public String getColumnName(int columnIndex) {
            if (columnIndex == 0) {
                return "C (-)";
            } else if (columnIndex == 1) {
                return "omega (THz)";
            } else {
                System.out.println("ResponseFunctionTableModel error: unknown column index");
                return "";
            }
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            if (columnIndex == 0) {
                return String.valueOf(m_data.get(rowIndex).getStrength());
            } else if (columnIndex == 1) {
                return String.valueOf(m_data.get(rowIndex).getFrequencyTHz());
            } else {
                System.out.println("ResponseFunctionTableModel error: unknown column index");
                return null;
            }
        }
        
        @Override
        public boolean isCellEditable(int row, int column) {
            return true;
        }
        
        @Override
        public void setValueAt(Object value, int rowIndex, int columnIndex) {
            if (columnIndex == 0) {
                m_data.get(rowIndex).setStrength(Utils.StringToDouble((String)value));
            } else if (columnIndex == 1) {
                m_data.get(rowIndex).setFrequencyTHz(Utils.StringToDouble((String)value));
            } else {
                System.out.println("ResponseFunctionTableModel error: unknown column index");
            }
            
            this.fireTableDataChanged();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton o_cancelButton;
    private javax.swing.JButton o_diel1Add;
    private javax.swing.JButton o_diel1Delete;
    private javax.swing.JButton o_diel2Add;
    private javax.swing.JButton o_diel2Delete;
    private javax.swing.JLabel o_dielHam;
    private javax.swing.JButton o_dielMAdd;
    private javax.swing.JButton o_dielMDelete;
    private javax.swing.JTextField o_dielMatsubara;
    private javax.swing.JTextField o_dielS;
    private javax.swing.JTable o_dielTableM;
    private javax.swing.JTable o_dielTableP1;
    private javax.swing.JTable o_dielTableP2;
    private javax.swing.JTextField o_dielTemp;
    private javax.swing.JButton o_okButton;
    // End of variables declaration//GEN-END:variables
}
